export interface Classification {
  categorySlug: string | null;
  regionSlug: string | null;
  marketSlug: string | null;
  tags: string[];
}

const CATEGORY_KEYWORDS: Record<string, string[]> = {
  elections: [
    "election",
    "campaign",
    "ballot",
    "candidate",
    "vote",
    "voting",
    "primary",
    "runoff",
    "polling",
    "poll",
    "race",
    "congressional",
    "senate race",
    "house race",
    "gubernatorial",
    "voters",
    "voter",
    "registration",
    "precinct",
    "absentee",
    "early voting",
    "results",
    "incumbent",
    "challenger",
    "senator",
    "representative",
    "house district",
    "senate district",
    "commissioner",
    "sheriff",
    "district attorney",
    "school board race",
    "bond referendum",
  ],
  legislature: [
    "general assembly",
    "senate",
    "house of representatives",
    "legislature",
    "legislator",
    "bill",
    "legislation",
    "committee",
    "session",
    "speaker",
    "majority leader",
    "minority leader",
    "state senate",
    "state house",
    "lawmakers",
    "law",
    "passes",
    "passed",
    "voted",
    "veto",
    "override",
    "appropriations",
    "budget bill",
    "SB",
    "HB",
    "house bill",
    "senate bill",
    "NC legislature",
    "floor vote",
    "crossover",
    "adjournment",
  ],
  government: [
    "governor",
    "agency",
    "department",
    "commission",
    "board",
    "appointed",
    "administration",
    "executive order",
    "cabinet",
    "state government",
    "Josh Stein",
    "Roy Cooper",
    "department of",
    "state budget",
    "executive",
    "state employee",
    "state agency",
    "NC DOT",
    "DHHS",
    "proclamation",
    "emergency declaration",
    "state contract",
    "audit",
    "state treasurer",
    "secretary of state",
    "lieutenant governor",
  ],
  courts: [
    "court",
    "judge",
    "ruling",
    "lawsuit",
    "legal",
    "supreme court",
    "appeals",
    "decision",
    "verdict",
    "judicial",
    "attorney general",
    "appeals court",
    "district court",
    "superior court",
    "federal court",
    "magistrate",
    "indicted",
    "indictment",
    "charged",
    "convicted",
    "sentencing",
    "civil rights",
    "injunction",
    "restraining order",
    "consent decree",
    "class action",
    "Fourth Circuit",
    "NC Supreme Court",
  ],
  education: [
    "school",
    "education",
    "university",
    "college",
    "unc",
    "nc state",
    "duke",
    "teacher",
    "student",
    "classroom",
    "curriculum",
    "board of education",
    "school board",
    "superintendent",
    "charter school",
    "public school",
    "private school",
    "voucher",
    "scholarship",
    "teacher pay",
    "standardized test",
    "graduation",
    "NC DPI",
    "State Board of Education",
    "community college",
    "NCCU",
    "Wake Forest",
    "Davidson",
    "Elon",
    "App State",
    "ECU",
    "UNCW",
    "NC Central",
  ],
  healthcare: [
    "health",
    "hospital",
    "medicaid",
    "medicare",
    "insurance",
    "healthcare",
    "mental health",
    "opioid",
    "drug",
    "medical",
    "Medicaid expansion",
    "Blue Cross",
    "nursing home",
    "substance abuse",
    "overdose",
    "NC Medicaid",
    "health care",
    "insurance premiums",
    "ACA",
    "vaccine",
    "public health",
    "CDC",
    "pandemic",
    "rural health",
    "NCDHHS",
  ],
  economy: [
    "economy",
    "jobs",
    "employment",
    "unemployment",
    "budget",
    "tax",
    "revenue",
    "business",
    "economic",
    "growth",
    "industry",
    "workforce",
    "unemployment rate",
    "job growth",
    "hiring",
    "layoffs",
    "manufacturing",
    "economic development",
    "incentive",
    "grant",
    "small business",
    "entrepreneurship",
    "poverty",
    "minimum wage",
    "income",
    "housing costs",
    "inflation",
    "interest rate",
    "commerce department",
    "NC Commerce",
    "site selection",
    "megasite",
  ],
  environment: [
    "environment",
    "climate",
    "energy",
    "pollution",
    "clean water",
    "conservation",
    "natural resources",
    "solar",
    "coal",
    "utilities",
    "Duke Energy",
    "PFAS",
    "GenX",
    "DEQ",
    "clean energy",
    "renewable",
    "wind farm",
    "solar farm",
    "coal ash",
    "water quality",
    "air quality",
    "EPA",
    "flooding",
    "hurricane",
    "storm surge",
    "sea level",
    "state park",
    "NC DEQ",
    "utilities commission",
  ],
  local: [
    "city council",
    "county commissioner",
    "mayor",
    "municipality",
    "local government",
    "zoning",
    "development",
    "city budget",
    "town council",
    "county budget",
    "planning board",
    "rezoning",
    "annexation",
    "road project",
    "fire department",
    "police department",
    "public works",
    "parks and recreation",
    "library",
    "county commission",
    "city manager",
    "HOA",
  ],
  politics: [
    "Republican",
    "Democrat",
    "GOP",
    "DNC",
    "RNC",
    "party",
    "endorsement",
    "fundraising",
    "PAC",
    "super PAC",
    "campaign finance",
    "approval rating",
    "swing district",
    "battleground",
    "gerrymandering",
    "redistricting",
    "political ad",
    "debate",
  ],
};

const REGION_KEYWORDS: Record<string, string[]> = {
  triangle: [
    "raleigh",
    "durham",
    "chapel hill",
    "cary",
    "wake county",
    "durham county",
    "orange county",
    "research triangle",
    "apex",
    "holly springs",
    "fuquay-varina",
    "morrisville",
    "wake forest",
    "garner",
    "clayton",
    "smithfield",
    "johnston county",
    "chatham county",
    "pittsboro",
  ],
  "charlotte-region": [
    "charlotte",
    "mecklenburg",
    "gastonia",
    "concord",
    "matthews",
    "huntersville",
    "mooresville",
    "rock hill",
    "fort mill",
    "ballantyne",
    "mint hill",
    "davidson",
    "cornelius",
    "lake norman",
    "cabarrus",
    "union county",
    "monroe",
    "kannapolis",
    "albemarle",
  ],
  triad: [
    "greensboro",
    "winston-salem",
    "high point",
    "guilford county",
    "forsyth county",
    "alamance",
    "burlington",
    "kernersville",
    "clemmons",
    "lexington",
    "davidson county",
    "stokes county",
    "rockingham county",
    "eden",
    "reidsville",
    "asheboro",
    "randolph county",
  ],
  "western-nc": [
    "asheville",
    "buncombe",
    "boone",
    "watauga",
    "cherokee",
    "bryson city",
    "hendersonville",
    "brevard",
    "western north carolina",
    "haywood county",
    "jackson county",
    "macon county",
    "swain county",
    "madison county",
    "yancey county",
    "mitchell county",
    "avery county",
    "waynesville",
    "sylva",
    "franklin",
    "murphy",
    "spruce pine",
    "newland",
    "banner elk",
  ],
  "coastal-nc": [
    "wilmington",
    "new hanover",
    "outer banks",
    "dare county",
    "morehead city",
    "beaufort",
    "jacksonville",
    "onslow",
    "brunswick county",
    "pender county",
    "carteret county",
    "onslow county",
    "camp lejeune",
    "topsail",
    "holden beach",
    "ocean isle",
    "sunset beach",
    "southport",
    "leland",
    "hampstead",
  ],
  "eastern-nc": [
    "greenville",
    "rocky mount",
    "wilson",
    "pitt county",
    "nash county",
    "edgecombe",
    "goldsboro",
    "wayne county",
    "kinston",
    "eastern north carolina",
    "lenoir county",
    "duplin county",
    "jones county",
    "craven county",
    "pamlico county",
    "washington nc",
    "bertie county",
    "hertford county",
    "northampton county",
    "roanoke rapids",
    "henderson",
    "oxford",
    "louisburg",
    "tarboro",
    "farmville",
  ],
  piedmont: [
    "burlington",
    "alamance",
    "randolph county",
    "asheboro",
    "sanford",
    "lee county",
  ],
  sandhills: [
    "fayetteville",
    "cumberland county",
    "pinehurst",
    "southern pines",
    "moore county",
    "fort bragg",
    "fort liberty",
  ],
};

const MARKET_KEYWORDS: Record<string, string[]> = {
  raleigh: ["raleigh", "wake county"],
  durham: ["durham"],
  "chapel-hill": ["chapel hill", "orange county"],
  charlotte: ["charlotte", "mecklenburg"],
  greensboro: ["greensboro", "guilford county"],
  "winston-salem": ["winston-salem", "forsyth county"],
  asheville: ["asheville", "buncombe county"],
  wilmington: ["wilmington", "new hanover"],
  fayetteville: ["fayetteville", "cumberland county"],
  greenville: ["greenville", "pitt county"],
  boone: ["boone", "watauga"],
};

function matchKeywords(
  text: string,
  keywords: Record<string, string[]>
): string | null {
  const lower = text.toLowerCase();
  let bestMatch: string | null = null;
  let bestCount = 0;

  for (const [key, words] of Object.entries(keywords)) {
    const count = words.filter((w) => lower.includes(w.toLowerCase())).length;
    if (count > bestCount) {
      bestCount = count;
      bestMatch = key;
    }
  }

  return bestCount > 0 ? bestMatch : null;
}

export function classifyArticle(
  title: string,
  summary?: string | null
): Classification {
  const text = `${title} ${summary || ""}`.toLowerCase();

  const categorySlug = matchKeywords(text, CATEGORY_KEYWORDS);
  const regionSlug = matchKeywords(text, REGION_KEYWORDS);
  const marketSlug = matchKeywords(text, MARKET_KEYWORDS);

  const tags: string[] = [];
  if (text.includes("republican") || text.includes(" gop "))
    tags.push("republican");
  if (text.includes("democrat")) tags.push("democrat");
  if (text.includes("bipartisan")) tags.push("bipartisan");
  if (text.includes("budget")) tags.push("budget");
  if (text.includes("election")) tags.push("elections");

  return { categorySlug, regionSlug, marketSlug, tags };
}
